### ISSUE TITLE
Why it can't download any plugin in "https://plugins.netbeans.apache.org/"

### ISSUE THREAD

**Issue by rfrkk** [lbruun/netbeans-explore-in-os#1]
No link to go,

screenshot
![Snipaste_2024-05-29_07-31-27](https://github.com/lbruun/netbeans-explore-in-os/assets/137764/f9e31135-89cb-4545-a9b6-98d13636cc82)

![Snipaste_2024-05-29_07-34-00](https://github.com/lbruun/netbeans-explore-in-os/assets/137764/e28b9000-1d87-4074-949d-81235f061a27)

**Comment by lbruun** [comment]
Thanks. Verification for later versions of the IDE (v20 -v22) had failed and I think the Plugin Portal then works in the way that it simply doesn't show this matrix then (for _any_ version of the IDE). Dunno. 

It now looks like this:

![image](https://github.com/lbruun/netbeans-explore-in-os/assets/32431476/1eafc961-fdc1-4b6c-ad80-3edec8f992fe)


The reason why verification had failed was that IDE Plugins (at least if they have the official verification sign on them) need to be signed. A new rule, I guess.
